### ISSUE TITLE
upload and download commands does not working

### ISSUE THREAD

**Issue by merlin123h** [0xmanjoos/Pieta#2]
Hi.
Please tell how to use upload and download commands.
I executed Upload command , but it shows upload command don't recognized.
Thanks

**Comment by 0xmanjoos** [comment]
Ah right about that.. Pieta is still in development, Im completely rewriting and redesigning the infrastructure behind this tool so I haven't really been supporting this much. There is much to be improved in this project, including the implementation of upload and download commands. So tldr; I'm workin on it :), thanks for checking out Pieta!
